[tool.poetry]
name = "django-public-web"
version = "0.1.0"
description = ""
authors = ["Ronit Nath <ronitnath@berkeley.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
Django = "^5.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
